// Copyright 2026 Glenn Lewis. All rights reserved.
//
// Use of this source code is governed by the Reticulum License
// that can be found in the LICENSE file.

package rns

import (
	_ "embed"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/gmlewis/go-reticulum/testutils"
)

//go:embed testdata/discovery_test.data
var discoveryTestData []byte

func TestListDiscoveredInterfaces(t *testing.T) {
	t.Parallel()
	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-")
	defer cleanup()
	storagePath := filepath.Join(tmpDir, "discovery", "interfaces")
	if err := os.MkdirAll(storagePath, 0o755); err != nil {
		t.Fatalf("failed to create storage path: %v", err)
	}

	// Write data generated by Python to the temporary storage path
	if err := os.WriteFile(filepath.Join(storagePath, "test_interface.data"), discoveryTestData, 0o644); err != nil {
		t.Fatalf("failed to write test data: %v", err)
	}

	r := &Reticulum{configDir: tmpDir}
	discovery := NewInterfaceDiscovery(r)

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}

	if len(discovered) != 1 {
		t.Fatalf("expected 1 discovered interface, got %v", len(discovered))
	}

	di := discovered[0]
	if di.Name != "Test Interface" {
		t.Errorf("expected name %q, got %q", "Test Interface", di.Name)
	}
	if di.Type != "UDPInterface" {
		t.Errorf("expected type %q, got %q", "UDPInterface", di.Type)
	}
	if di.Hops != 1 {
		t.Errorf("expected 1 hop, got %v", di.Hops)
	}
	if !di.Transport {
		t.Errorf("expected transport enabled")
	}
	if di.Latitude == nil || *di.Latitude != 34.0522 {
		t.Errorf("expected latitude 34.0522, got %v", di.Latitude)
	}
	if di.Longitude == nil || *di.Longitude != -118.2437 {
		t.Errorf("expected longitude -118.2437, got %v", di.Longitude)
	}
	if di.Height == nil || *di.Height != 100 {
		t.Errorf("expected height 100, got %v", di.Height)
	}
	if di.Value != 1000 {
		t.Errorf("expected value 1000, got %v", di.Value)
	}
	// Note that `Status` depends on the current time.
}

func TestListDiscoveredInterfaces_StatusThresholds(t *testing.T) {
	t.Parallel()
	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-status-")
	defer cleanup()
	storagePath := filepath.Join(tmpDir, "discovery", "interfaces")
	if err := os.MkdirAll(storagePath, 0o755); err != nil {
		t.Fatalf("failed to create storage path: %v", err)
	}

	now := float64(time.Now().UnixNano()) / 1e9

	// Available: heard 1 hour ago
	availableData := map[string]any{
		"name":       "Available",
		"last_heard": now - 3600,
	}
	// Unknown: heard 2 days ago
	unknownData := map[string]any{
		"name":       "Unknown",
		"last_heard": now - (ThresholdUnknown + 3600),
	}
	// Stale: heard 4 days ago
	staleData := map[string]any{
		"name":       "Stale",
		"last_heard": now - (ThresholdStale + 3600),
	}
	// Expired: heard 8 days ago (should be removed)
	expiredData := map[string]any{
		"name":       "Expired",
		"last_heard": now - (ThresholdRemove + 3600),
	}

	writeData := func(name string, m map[string]any) {
		path := filepath.Join(storagePath, name+".data")
		data := mustMsgpackPack(m)
		if err := os.WriteFile(path, data, 0o644); err != nil {
			t.Fatalf("failed to write %v data: %v", name, err)
		}
	}

	writeData("available", availableData)
	writeData("unknown", unknownData)
	writeData("stale", staleData)
	writeData("expired", expiredData)

	r := &Reticulum{configDir: tmpDir}
	discovery := NewInterfaceDiscovery(r)

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}

	if len(discovered) != 3 {
		t.Fatalf("expected 3 discovered interfaces (1 removed), got %v", len(discovered))
	}

	statusMap := make(map[string]string)
	for _, di := range discovered {
		statusMap[di.Name] = di.Status
	}

	if statusMap["Available"] != "available" {
		t.Errorf("Available: expected status available, got %q", statusMap["Available"])
	}
	if statusMap["Unknown"] != "unknown" {
		t.Errorf("Unknown: expected status unknown, got %q", statusMap["Unknown"])
	}
	if statusMap["Stale"] != "stale" {
		t.Errorf("Stale: expected status stale, got %q", statusMap["Stale"])
	}

	// Verify expired file was removed
	if _, err := os.Stat(filepath.Join(storagePath, "expired.data")); !os.IsNotExist(err) {
		t.Errorf("expected expired file to be removed")
	}
}
