// Copyright 2026 Glenn Lewis. All rights reserved.
//
// Use of this source code is governed by the Reticulum License
// that can be found in the LICENSE file.

package rns

import (
	_ "embed"
	"encoding/hex"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"github.com/gmlewis/go-reticulum/rns/msgpack"
	"github.com/gmlewis/go-reticulum/testutils"
)

//go:embed testdata/discovery_test.data
var discoveryTestData []byte

func TestListDiscoveredInterfaces(t *testing.T) {
	t.Parallel()
	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-")
	defer cleanup()
	storagePath := filepath.Join(tmpDir, "discovery", "interfaces")
	if err := os.MkdirAll(storagePath, 0o755); err != nil {
		t.Fatalf("failed to create storage path: %v", err)
	}

	fixture := normalizeDiscoveryFixtureTimes(t, discoveryTestData)

	// Write data generated by Python to the temporary storage path.
	if err := os.WriteFile(filepath.Join(storagePath, "test_interface.data"), fixture, 0o644); err != nil {
		t.Fatalf("failed to write test data: %v", err)
	}

	r := &Reticulum{configDir: tmpDir}
	discovery := NewInterfaceDiscovery(r)

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}

	if len(discovered) != 1 {
		t.Fatalf("expected 1 discovered interface, got %v", len(discovered))
	}

	di := discovered[0]
	if di.Name != "Test Interface" {
		t.Errorf("expected name %q, got %q", "Test Interface", di.Name)
	}
	if di.Type != "UDPInterface" {
		t.Errorf("expected type %q, got %q", "UDPInterface", di.Type)
	}
	if di.Hops != 1 {
		t.Errorf("expected 1 hop, got %v", di.Hops)
	}
	if !di.Transport {
		t.Errorf("expected transport enabled")
	}
	if di.Latitude == nil || *di.Latitude != 34.0522 {
		t.Errorf("expected latitude 34.0522, got %v", di.Latitude)
	}
	if di.Longitude == nil || *di.Longitude != -118.2437 {
		t.Errorf("expected longitude -118.2437, got %v", di.Longitude)
	}
	if di.Height == nil || *di.Height != 100 {
		t.Errorf("expected height 100, got %v", di.Height)
	}
	if di.Value != 1000 {
		t.Errorf("expected value 1000, got %v", di.Value)
	}
	// Note that `Status` depends on the current time.
}

func normalizeDiscoveryFixtureTimes(t *testing.T, data []byte) []byte {
	t.Helper()

	unpacked, err := msgpack.Unpack(data)
	if err != nil {
		t.Fatalf("failed to unpack discovery fixture: %v", err)
	}
	m := asAnyMap(unpacked)
	if m == nil {
		t.Fatalf("unexpected discovery fixture type %T", unpacked)
	}

	now := float64(time.Now().UnixNano()) / 1e9
	m["discovered"] = now - 7200
	m["last_heard"] = now - 3600
	return mustMsgpackPack(m)
}

func TestListDiscoveredInterfaces_StatusThresholds(t *testing.T) {
	t.Parallel()
	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-status-")
	defer cleanup()
	storagePath := filepath.Join(tmpDir, "discovery", "interfaces")
	if err := os.MkdirAll(storagePath, 0o755); err != nil {
		t.Fatalf("failed to create storage path: %v", err)
	}

	now := float64(time.Now().UnixNano()) / 1e9

	// Available: heard 1 hour ago
	availableData := map[string]any{
		"name":       "Available",
		"last_heard": now - 3600,
	}
	// Unknown: heard 2 days ago
	unknownData := map[string]any{
		"name":       "Unknown",
		"last_heard": now - (ThresholdUnknown + 3600),
	}
	// Stale: heard 4 days ago
	staleData := map[string]any{
		"name":       "Stale",
		"last_heard": now - (ThresholdStale + 3600),
	}
	// Expired: heard 8 days ago (should be removed)
	expiredData := map[string]any{
		"name":       "Expired",
		"last_heard": now - (ThresholdRemove + 3600),
	}

	writeData := func(name string, m map[string]any) {
		path := filepath.Join(storagePath, name+".data")
		data := mustMsgpackPack(m)
		if err := os.WriteFile(path, data, 0o644); err != nil {
			t.Fatalf("failed to write %v data: %v", name, err)
		}
	}

	writeData("available", availableData)
	writeData("unknown", unknownData)
	writeData("stale", staleData)
	writeData("expired", expiredData)

	r := &Reticulum{configDir: tmpDir}
	discovery := NewInterfaceDiscovery(r)

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}

	if len(discovered) != 3 {
		t.Fatalf("expected 3 discovered interfaces (1 removed), got %v", len(discovered))
	}

	statusMap := make(map[string]string)
	for _, di := range discovered {
		statusMap[di.Name] = di.Status
	}

	if statusMap["Available"] != "available" {
		t.Errorf("Available: expected status available, got %q", statusMap["Available"])
	}
	if statusMap["Unknown"] != "unknown" {
		t.Errorf("Unknown: expected status unknown, got %q", statusMap["Unknown"])
	}
	if statusMap["Stale"] != "stale" {
		t.Errorf("Stale: expected status stale, got %q", statusMap["Stale"])
	}

	// Verify expired file was removed
	if _, err := os.Stat(filepath.Join(storagePath, "expired.data")); !os.IsNotExist(err) {
		t.Errorf("expected expired file to be removed")
	}
}

func TestListDiscoveredInterfaces_SourceAndReachableFiltering(t *testing.T) {
	t.Parallel()

	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-filter-")
	defer cleanup()
	storagePath := filepath.Join(tmpDir, "discovery", "interfaces")
	if err := os.MkdirAll(storagePath, 0o755); err != nil {
		t.Fatalf("failed to create storage path: %v", err)
	}

	now := float64(time.Now().UnixNano()) / 1e9
	sourceHex := "0102030405060708090a0b0c0d0e0f10"
	sourceBytes, err := hex.DecodeString(sourceHex)
	if err != nil {
		t.Fatalf("DecodeString(sourceHex) error = %v", err)
	}

	writeData := func(name string, m map[string]any) {
		path := filepath.Join(storagePath, name+".data")
		if err := os.WriteFile(path, mustMsgpackPack(m), 0o644); err != nil {
			t.Fatalf("failed to write %v data: %v", name, err)
		}
	}

	writeData("matching", map[string]any{
		"name":         "Matching",
		"last_heard":   now - 3600,
		"network_id":   sourceHex,
		"reachable_on": "discovery.example.net",
	})
	writeData("missing-network-id", map[string]any{
		"name":       "MissingNetworkID",
		"last_heard": now - 3600,
	})
	writeData("wrong-network-id", map[string]any{
		"name":       "WrongNetworkID",
		"last_heard": now - 3600,
		"network_id": "ffeeddccbbaa00998877665544332211",
	})
	writeData("invalid-reachable", map[string]any{
		"name":         "InvalidReachable",
		"last_heard":   now - 3600,
		"network_id":   sourceHex,
		"reachable_on": "not a hostname!",
	})

	r := &Reticulum{
		configDir:        tmpDir,
		interfaceSources: [][]byte{sourceBytes},
	}
	discovery := NewInterfaceDiscovery(r)

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}
	if len(discovered) != 1 {
		t.Fatalf("expected 1 discovered interface after filtering, got %v", len(discovered))
	}
	if discovered[0].Name != "Matching" {
		t.Fatalf("unexpected surviving interface %q", discovered[0].Name)
	}

	for _, name := range []string{"missing-network-id.data", "wrong-network-id.data", "invalid-reachable.data"} {
		if _, err := os.Stat(filepath.Join(storagePath, name)); !os.IsNotExist(err) {
			t.Fatalf("expected filtered discovery file %q to be removed", name)
		}
	}
}

func TestListDiscoveredInterfaces_SortsLikePython(t *testing.T) {
	t.Parallel()

	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-sort-")
	defer cleanup()
	storagePath := filepath.Join(tmpDir, "discovery", "interfaces")
	if err := os.MkdirAll(storagePath, 0o755); err != nil {
		t.Fatalf("failed to create storage path: %v", err)
	}

	now := float64(time.Now().UnixNano()) / 1e9
	writeData := func(name string, m map[string]any) {
		path := filepath.Join(storagePath, name+".data")
		if err := os.WriteFile(path, mustMsgpackPack(m), 0o644); err != nil {
			t.Fatalf("failed to write %v data: %v", name, err)
		}
	}

	writeData("stale-high-value", map[string]any{
		"name":       "StaleHighValue",
		"last_heard": now - (ThresholdStale + 3600),
		"value":      5000,
	})
	writeData("available-lower-value", map[string]any{
		"name":       "AvailableLowerValue",
		"last_heard": now - 3600,
		"value":      1000,
	})
	writeData("available-higher-value", map[string]any{
		"name":       "AvailableHigherValue",
		"last_heard": now - 1800,
		"value":      2000,
	})
	writeData("available-same-value-older", map[string]any{
		"name":       "AvailableSameValueOlder",
		"last_heard": now - 2400,
		"value":      2000,
	})
	writeData("unknown-high-value", map[string]any{
		"name":       "UnknownHighValue",
		"last_heard": now - (ThresholdUnknown + 3600),
		"value":      8000,
	})

	r := &Reticulum{configDir: tmpDir}
	discovery := NewInterfaceDiscovery(r)

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}

	if got, want := len(discovered), 5; got != want {
		t.Fatalf("expected %v discovered interfaces, got %v", want, got)
	}

	gotNames := []string{
		discovered[0].Name,
		discovered[1].Name,
		discovered[2].Name,
		discovered[3].Name,
		discovered[4].Name,
	}
	wantNames := []string{
		"AvailableHigherValue",
		"AvailableSameValueOlder",
		"AvailableLowerValue",
		"UnknownHighValue",
		"StaleHighValue",
	}
	for i, want := range wantNames {
		if gotNames[i] != want {
			t.Fatalf("discovered[%v] name = %q, want %q (full order %v)", i, gotNames[i], want, gotNames)
		}
	}
}

func TestPersistDiscoveredInterface_NewEntry(t *testing.T) {
	t.Parallel()

	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-persist-new-")
	defer cleanup()

	r := &Reticulum{configDir: tmpDir}
	discovery := NewInterfaceDiscovery(r)
	receivedAt := float64(time.Now().UnixNano()) / 1e9
	info := map[string]any{
		"name":           "Persisted",
		"type":           "TCPServerInterface",
		"received":       receivedAt,
		"discovery_hash": []byte{0xaa, 0xbb, 0xcc},
		"value":          1234,
	}

	if err := discovery.persistDiscoveredInterface(info); err != nil {
		t.Fatalf("persistDiscoveredInterface failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(tmpDir, "discovery", "interfaces", "aabbcc.data"))
	if err != nil {
		t.Fatalf("failed to read persisted discovery file: %v", err)
	}
	unpacked, err := msgpack.Unpack(data)
	if err != nil {
		t.Fatalf("failed to unpack persisted discovery file: %v", err)
	}
	m := asAnyMap(unpacked)
	if m == nil {
		t.Fatalf("unexpected persisted discovery type %T", unpacked)
	}

	if got := asFloat64(lookupAnyValue(m, "discovered")); got != receivedAt {
		t.Fatalf("discovered = %v, want %v", got, receivedAt)
	}
	if got := asFloat64(lookupAnyValue(m, "last_heard")); got != receivedAt {
		t.Fatalf("last_heard = %v, want %v", got, receivedAt)
	}
	if got := asInt(lookupAnyValue(m, "heard_count")); got != 0 {
		t.Fatalf("heard_count = %v, want 0", got)
	}
}

func TestPersistDiscoveredInterface_ExistingEntryPreservesDiscoveryTime(t *testing.T) {
	t.Parallel()

	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-persist-existing-")
	defer cleanup()

	r := &Reticulum{configDir: tmpDir}
	discovery := NewInterfaceDiscovery(r)
	initialReceived := float64(time.Now().UnixNano()) / 1e9
	info := map[string]any{
		"name":           "Persisted",
		"type":           "TCPServerInterface",
		"received":       initialReceived,
		"discovery_hash": "aabbcc",
		"value":          1234,
	}

	if err := discovery.persistDiscoveredInterface(info); err != nil {
		t.Fatalf("first persistDiscoveredInterface failed: %v", err)
	}

	secondReceived := initialReceived + 60
	if err := discovery.persistDiscoveredInterface(map[string]any{
		"name":           "Persisted",
		"type":           "TCPServerInterface",
		"received":       secondReceived,
		"discovery_hash": "aabbcc",
		"value":          5678,
	}); err != nil {
		t.Fatalf("second persistDiscoveredInterface failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(tmpDir, "discovery", "interfaces", "aabbcc.data"))
	if err != nil {
		t.Fatalf("failed to read persisted discovery file: %v", err)
	}
	unpacked, err := msgpack.Unpack(data)
	if err != nil {
		t.Fatalf("failed to unpack persisted discovery file: %v", err)
	}
	m := asAnyMap(unpacked)
	if m == nil {
		t.Fatalf("unexpected persisted discovery type %T", unpacked)
	}

	if got := asFloat64(lookupAnyValue(m, "discovered")); got != initialReceived {
		t.Fatalf("discovered = %v, want %v", got, initialReceived)
	}
	if got := asFloat64(lookupAnyValue(m, "last_heard")); got != secondReceived {
		t.Fatalf("last_heard = %v, want %v", got, secondReceived)
	}
	if got := asInt(lookupAnyValue(m, "heard_count")); got != 1 {
		t.Fatalf("heard_count = %v, want 1", got)
	}
	if got := asInt(lookupAnyValue(m, "value")); got != 5678 {
		t.Fatalf("value = %v, want 5678", got)
	}
}

func TestInterfaceDiscoveryReceiveAndPersist(t *testing.T) {
	t.Parallel()

	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-receive-")
	defer cleanup()

	ts := NewTransportSystem(nil)
	destinationHash := []byte("discovery-destination")
	ts.pathTable[string(destinationHash)] = &PathEntry{Hops: 2, Expires: time.Now().Add(time.Hour)}

	r := &Reticulum{
		configDir: tmpDir,
		transport: ts,
		logger:    NewLogger(),
	}
	discovery := NewInterfaceDiscovery(r)

	sourceIdentity := mustTestNewIdentity(t, true)
	transportID := []byte{0xde, 0xad, 0xbe, 0xef}
	appData := mustDiscoveryAnnounceAppData(t, map[any]any{
		discoveryFieldInterfaceType: "TCPServerInterface",
		discoveryFieldTransport:     true,
		discoveryFieldTransportID:   transportID,
		discoveryFieldName:          "Discovered TCP",
		discoveryFieldReachableOn:   "discovery.example.net",
		discoveryFieldPort:          4242,
		discoveryFieldIFACNetname:   "mesh",
		discoveryFieldIFACNetkey:    "secret",
	}, 2)

	var callbackErr error
	handler := NewInterfaceAnnounceHandler(r, 2, func(info map[string]any) {
		callbackErr = discovery.persistDiscoveredInterface(info)
	})

	handler.receivedAnnounce(destinationHash, sourceIdentity, appData)
	if callbackErr != nil {
		t.Fatalf("persist callback failed: %v", callbackErr)
	}

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}
	if got, want := len(discovered), 1; got != want {
		t.Fatalf("expected %v discovered interface, got %v", want, got)
	}

	got := discovered[0]
	if got.Name != "Discovered TCP" {
		t.Fatalf("Name = %q, want %q", got.Name, "Discovered TCP")
	}
	if got.Type != "TCPServerInterface" {
		t.Fatalf("Type = %q, want %q", got.Type, "TCPServerInterface")
	}
	if got.Hops != 2 {
		t.Fatalf("Hops = %v, want 2", got.Hops)
	}
	if got.TransportID != "deadbeef" {
		t.Fatalf("TransportID = %q, want %q", got.TransportID, "deadbeef")
	}
	if got.NetworkID != sourceIdentity.HexHash {
		t.Fatalf("NetworkID = %q, want %q", got.NetworkID, sourceIdentity.HexHash)
	}
	if got.ReachableOn != "discovery.example.net" {
		t.Fatalf("ReachableOn = %q, want %q", got.ReachableOn, "discovery.example.net")
	}
	if got.Port == nil || *got.Port != 4242 {
		t.Fatalf("Port = %v, want 4242", got.Port)
	}
	if got.Value < 2 {
		t.Fatalf("Value = %v, want >= 2", got.Value)
	}

	connectionType := "BackboneInterface"
	remoteKey := "remote"
	if runtime.GOOS == "windows" {
		connectionType = "TCPClientInterface"
		remoteKey = "target_host"
	}
	wantConfigEntry := "[[Discovered TCP]]\n  type = " + connectionType +
		"\n  enabled = yes\n  " + remoteKey + " = discovery.example.net\n  target_port = 4242" +
		"\n  transport_identity = deadbeef\n  network_name = mesh\n  passphrase = secret"
	if got.ConfigEntry != wantConfigEntry {
		t.Fatalf("ConfigEntry = %q, want %q", got.ConfigEntry, wantConfigEntry)
	}
}

func TestInterfaceDiscoveryReceiveAndPersistRejectsInsufficientStampValue(t *testing.T) {
	t.Parallel()

	tmpDir, cleanup := testutils.TempDir(t, "rns-discovery-receive-invalid-")
	defer cleanup()

	ts := NewTransportSystem(nil)
	r := &Reticulum{
		configDir: tmpDir,
		transport: ts,
		logger:    NewLogger(),
	}
	discovery := NewInterfaceDiscovery(r)

	callbackCalled := false
	handler := NewInterfaceAnnounceHandler(r, 20, func(info map[string]any) {
		callbackCalled = true
	})

	sourceIdentity := mustTestNewIdentity(t, true)
	appData := mustDiscoveryAnnounceAppData(t, map[any]any{
		discoveryFieldInterfaceType: "TCPServerInterface",
		discoveryFieldTransport:     true,
		discoveryFieldTransportID:   []byte{0xde, 0xad, 0xbe, 0xef},
		discoveryFieldName:          "Broken",
		discoveryFieldReachableOn:   "discovery.example.net",
		discoveryFieldPort:          4242,
	}, 2)

	handler.receivedAnnounce([]byte("discovery-destination"), sourceIdentity, appData)
	if callbackCalled {
		t.Fatal("expected insufficient-value stamp announce to be ignored")
	}

	discovered, err := discovery.ListDiscoveredInterfaces(false, false)
	if err != nil {
		t.Fatalf("ListDiscoveredInterfaces failed: %v", err)
	}
	if len(discovered) != 0 {
		t.Fatalf("expected no persisted discovered interfaces, got %v", len(discovered))
	}
}

func mustDiscoveryAnnounceAppData(t *testing.T, payload map[any]any, targetCost int) []byte {
	t.Helper()

	packed, err := msgpack.Pack(payload)
	if err != nil {
		t.Fatalf("msgpack.Pack(payload) error = %v", err)
	}
	stamp, _, err := generateDiscoveryStamp(FullHash(packed), targetCost)
	if err != nil {
		t.Fatalf("generateDiscoveryStamp error = %v", err)
	}

	appData := make([]byte, 1, 1+len(packed)+len(stamp))
	appData[0] = 0
	appData = append(appData, packed...)
	appData = append(appData, stamp...)
	return appData
}
